### ISSUE TITLE
windows error when installing on Linux Fedora 38

### ISSUE THREAD

**Issue by mariusa** [newrelic/ansible-install#40]
[NOTE]: # ( ^^ Provide a general summary of the issue in the title above. ^^ )

newrelic.yml 
```
---
# https://github.com/newrelic/infrastructure-agent-ansible/issues/206
# By default, the infrastructure agent doesn't send data about the operating system's processes. To enable the sending of process data set enable_process_metrics to true. To fine-tune which processes you want to monitor, configure include_matching_metrics.
- hosts: localhost
  become: yes
  gather_facts: yes
  roles:
    - role: newrelic.newrelic_install
      vars:
        log_file: /var/log/newrelic/newrelic.log
        nrinfragent_state: latest
        nrinfragent_config:
          enable_process_metrics: true
          license_key: ABC
        nrinfragent_integrations:
        # The integrations package name is located in the Install and activate section of the individual integrations docs.
          - name: nri-nginx
            state: latest
```

## Description
```
# ansible-playbook newrelic.yml 
[WARNING]: provided hosts list is empty, only localhost is available. Note that the implicit localhost does not match 'all'
ERROR! couldn't resolve module/action 'ansible.windows.win_file'. This often indicates a misspelling, missing collection, or incorrect module path.

The error appears to be in '/root/.ansible/roles/newrelic.newrelic_install/tasks/windows.yml': line 14, column 3, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:


- name: Touch verbose output log file
  ^ here
```

Thanks

**Comment by rthorn-nr** [comment]
Hi @mariusa , based on your example playbook, I think you're looking for `newrelic.newrelic-infra` https://galaxy.ansible.com/newrelic/newrelic-infra

**Comment by mariusa** [comment]
Here's the updated ansible script for this version, same issue:
```
---
- hosts: localhost
  become: yes
  gather_facts: yes # https://stackoverflow.com/questions/73463325/gather-facts-seems-to-break-set-fact-and-hostvars
  roles:
    - role: newrelic.newrelic_install
      vars:
        targets:
          - infrastructure
          - logs
        install_timeout_seconds: 3000
        verbosity: debug
  environment:
    NEW_RELIC_API_KEY: "..."
    NEW_RELIC_ACCOUNT_ID: "..."
    NEW_RELIC_REGION: "US"
    NEW_RELIC_APPLICATION_NAME: "..."
```

```
ERROR! couldn't resolve module/action 'ansible.windows.win_file'. This often indicates a misspelling, missing collection, or incorrect module path.

The error appears to be in '/root/.ansible/roles/newrelic.newrelic_install/tasks/windows.yml': line 14, column 3, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:


- name: Touch verbose output log file
  ^ here
```
