### ISSUE TITLE
Even though install_timeout_seconds is not defined it still gives an error

### ISSUE THREAD

**Issue by mramadan-modernise** [newrelic/ansible-install#41]
## Description

[NOTE]: # ( Describe the problem you're encountering. )
[TIP]:  # ( Do NOT give us access or passwords to your New Relic account or API keys! )

## Steps to Reproduce

given the below playbook

```
---
- name: Install New Relic infrastructure and logs
  hosts: all
  roles:
  - role: newrelic.newrelic_install
  vars:
    targets:
    - infrastructure
    verbosity: debug
  environment:
    NEW_RELIC_API_KEY: '...'
    NEW_RELIC_ACCOUNT_ID: '...'
    NEW_RELIC_REGION: US
```

Got the following error:

```
fatal: [app]: FAILED! => {"msg": "The conditional check 'install_timeout_seconds is not defined or install_timeout_seconds is integer' failed. The error was: template error while templating string: no test named 'integer'. String: {% if install_timeout_seconds is not defined or install_timeout_seconds is integer %} True {% else %} False {% endif %}"}
```

## Expected Behavior

Validation is passed and agent is installed

## Relevant Logs / Console output

```
fatal: [app]: FAILED! => {"msg": "The conditional check 'install_timeout_seconds is not defined or install_timeout_seconds is integer' failed. The error was: template error while templating string: no test named 'integer'. String: {% if install_timeout_seconds is not defined or install_timeout_seconds is integer %} True {% else %} False {% endif %}"}
```

## Your Environment

* Module version: v0.3.0
* Ansible version: 2.12.10
