### ISSUE TITLE
Ask: How to skip `newrelic_install` when nothing was changed? 🙏

### ISSUE THREAD

**Issue by meotimdihia** [newrelic/ansible-install#61]
I have this task. There is a way to skip `the role` when nothing was changed in Ansible? (the role took a lot of time)
But I also want it to reinstall when I change `targets` 

```
tasks:
    - name: Install newrelic
      ansible.builtin.import_role:
        name: "newrelic.newrelic_install"
      vars:
        targets:
          - infrastructure
          - logs
      tags: ["newrelic"]
```
