### ISSUE TITLE
ask: proxy setting in newrelic-infra.yml

### ISSUE THREAD

**Issue by 8mccm8** [newrelic/ansible-install#62]
HI all

how can I setup proxy in /etc/newrelic-infra.yml ?

thanks

**Comment by 8mccm8** [comment]
HI @amolero-nr 

I set `HTTPS_PROXY` and the installation was done correctly BUT the `proxy` directive was not set in `/etc/newrelic-infra.yml` and my gent can't send metrics to the API...

I willl check again tomorrow.

**Comment by amolero-nr** [comment]
Hey @8mccm8,

In my test, after setting the `HTTPS_PROXY` env var like this below in my playbook: 

```
- name: Install New Relic
  hosts: linux
  roles:
    - role: newrelic.newrelic_install
      vars:
        targets:
          - infrastructure
          - logs
      environment:
        NEW_RELIC_API_KEY: "..."
        NEW_RELIC_ACCOUNT_ID: "..."
        NEW_RELIC_REGION: "..."
        HTTPS_PROXY: "http://MY_PROXY:PORT"
```

I got the `config` option successfully added to my `newrelic-infra.yml` as follows:

```
enable_process_metrics: true
status_server_enabled: true
status_server_port: 18003
license_key: < ... >
custom_attributes:
  nr_deployed_by: ansible-install

proxy: http://172.31.45.182:3128         #  <-- HERE
```
