### ISSUE TITLE
Trusted.gpg deprecation in future Ubuntu versions

### ISSUE THREAD

**Issue by dcruzrinkel** [newrelic/ansible-install#77]
## Summary

```
W: https://download.newrelic.com/infrastructure_agent/linux/apt/dists/jammy/InRelease: Key is stored in legacy trusted.gpg keyring (/etc/apt/trusted.gpg), see the DEPRECATION section in apt-key(8) for details.
```

Ubuntu 24.04 will be released next April and it will include a deprecation for the trusted.gpg files.

## Desired Behavior

GPG keys should be included in /usr/share/keyrings or /etc/apt/keyrings and then included in the repo file.

```
deb [signed-by=/etc/apt/trusted.gpg.d/GPGkey] https://whatever_repo stable main
```

About the right location for GPG keys.

```
/usr/share/keyrings for keyrings managed by packages, and /etc/apt/keyrings for keyrings managed by the system operator.
```

## Possible Solution

- Download GPG key to /usr/share/keyrings and reference it in newrelic repo file. Or download it to a temporal folder and import it with `gpg --no-default-keyring --keyring gnupg-ring:/tmp/newrelic-infra.gpg --import`

## Additional context

We receive a warning right now, but in a couple of months this will be mandatory when updating. The updated method will also work (at least) in Ubuntu 22.04.

**Comment by burner1024** [comment]
24.04 is long released.
I'll throw in more warnings:

```
W: https://download.newrelic.com/infrastructure_agent/linux/apt/dists/noble/InRelease: Key is stored in legacy trusted.gpg keyring (/etc/apt/trusted.gpg), see the DEPRECATION section in apt-key(8) for details.
W: http://apt.newrelic.com/debian/dists/newrelic/Release.gpg: Key is stored in legacy trusted.gpg keyring (/etc/apt/trusted.gpg), see the DEPRECATION section in apt-key(8) for details.
W: http://apt.newrelic.com/debian/dists/newrelic/Release.gpg: Signature by key B60A3EC9BC013B9C23790EC8B31B29E5548C16BF uses weak algorithm (dsa1024)
N: Missing Signed-By in the sources.list(5) entry for 'http://apt.newrelic.com/debian'
N: Missing Signed-By in the sources.list(5) entry for 'https://download.newrelic.com/infrastructure_agent/linux/apt'
```

Please make the corresponding updates, it just looks not very professional.

**Comment by edpittol** [comment]
These tasks solved the issue to me. It is based on the [PHP agent installation documentation](https://docs.newrelic.com/docs/apm/agents/php-agent/installation/php-agent-installation-ubuntu-debian/).

```yaml
  - name: Add New Relic GPG key
    ansible.builtin.apt_key:
      id: B60A3EC9BC013B9C23790EC8B31B29E5548C16BF
      url: https://download.newrelic.com/548C16BF.gpg
      keyring: "{{ newrelic_apt_keyring }}"
      state: present
  - name: Remove New Relic APT repository
    ansible.builtin.apt_repository:
      repo: "deb http://apt.newrelic.com/debian/ newrelic non-free"
      filename: "{{ newrelic_apt_filename }}"
      state: absent
      update_cache: false
  - name: Add New Relic APT repository
    ansible.builtin.apt_repository:
      repo: "deb [signed-by={{ newrelic_apt_keyring }}] http://apt.newrelic.com/debian/ newrelic non-free"
      filename: "{{ newrelic_apt_filename }}"
      state: present
      update_cache: true
```

Vars values:

```
newrelic_apt_keyring: /usr/share/keyrings/download.newrelic.com-newrelic.gpg
newrelic_apt_filename: newrelic
```
