### ISSUE TITLE
Missing `VARNISH` support in Ansible role

### ISSUE THREAD

**Issue by lbajsarowicz** [newrelic/ansible-install#97]
[NOTE]: # ( ^^ Provide a general summary of the request in the title above. ^^ )

## Summary

[NOTE]: # ( Provide a brief overview of what the new feature is all about. )

I have tried to install this in 2 different ways:
```yaml
      vars:
        log_file: /var/log/newrelic-infra.log
        verbose: 0
        target_names:
          # Add other nri-* names here if mysql/nginx are also handled this way
          - nri-varnish # Use the canonical nri- name
        targets:
          - infrastructure
          - logs
          - apm-php
          # Potentially remove mysql and nginx if they should be in target_names as nri-mysql, nri-nginx
          - mysql
          - nginx
```

and

```yaml
      vars:
        log_file: /var/log/newrelic-infra.log
        verbose: 0
        # It's recommended to remove or comment out the 'target_names' variable
        # if 'varnish' is added to 'targets', as its current value is likely incorrect
        # for installing the Varnish integration.
        # target_names:
        #   - varnish-cache-open-source-integration
        targets:
          - infrastructure
          - logs
          - apm-php
          - mysql
          - nginx
          - varnish  # <-- Add 'varnish' here
```

both did not work.

Eventually the following failed too:
```

      vars:
        log_file: /var/log/newrelic-infra.log
        verbose: 0
        target_names:
          - varnish-cache-open-source-integration
        targets:
          - infrastructure
          - logs
          - apm-php
          - mysql
          - nginx
```

## Desired Behavior

1. There is a way to install Varnish integration using Ansible role for NewRelic.

[NOTE]: # ( Tell us how the new feature should work. Be specific. )
[TIP]:  # ( Do NOT give us access or passwords to your New Relic account or API keys! )

## Possible Solution

[NOTE]: # ( Not required. Suggest how to implement the addition or change. )

## Additional context

[TIP]:  # ( Why does this feature matter to you? What unique circumstances do you have? )
